# Generated by Django 4.2.7 on 2023-11-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_last_changing',
            field=models.DateField(verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_purchase',
            field=models.DateField(verbose_name='Дата покупки'),
        ),
    ]
