# Generated by Django 4.2.7 on 2023-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_date_of_last_changing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_last_changing',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
    ]
