# Generated by Django 4.2.7 on 2023-11-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_date_of_last_changing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_of_purchase',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_last_changing',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
